language: python

python:
  - "3.6"

before_install:
  - python setup.py deep-clean
  - python setup.py createvenv
  - source venv/bin/activate

install: 
  - python setup.py build-only

script:
  - cd ..
  - python setup.py loadtestdata